export enum languages {
       German = 'German'
,  English = 'English'
,  Romanian = 'Romanian'
,  Danish = 'Danish'
,  Israeli = 'Israeli'
,  French = 'French'
,  Italian = 'Italian'
,  Spanish = 'Spanish'
,  Russian = 'Russian'
,  Hungarian = 'Hungarian'
,  Turkish = 'Turkish'
,  Polish = 'Polish'
,  Greek = 'Greek'
,  Bulgarian = 'Bulgarian'
,  Serbian = 'Serbian'
,  Swedish = 'Swedish'
,  Norwegian = 'Norwegian'
,  Chinese = 'Chinese'
,  Japanese = 'Japanese'
,  Arabic = 'Arabic'

   }