export enum logcommand {
       ContactInfo = 'ContactInfo'
,  DestinationResource = 'DestinationResource'
,  TravelGroup = 'TravelGroup'
,  TouristResource = 'TouristResource'
,  TripOfferResource = 'TripOfferResource'
,  Login = 'Login'
,  Logout = 'Logout'
,  Tourist = 'Tourist'
,  Guide = 'Guide'
,  GuideResource = 'GuideResource'
,  Agency = 'Agency'
,  User = 'User'
,  Publisher = 'Publisher'
,  Bid = 'Bid'
,  PriceInfo = 'PriceInfo'
,  HostResource = 'HostResource'
,  EventResource = 'EventResource'
,  Presentation = 'Presentation'
,  AccomodationResource = 'AccomodationResource'
,  AccomodationCalendar = 'AccomodationCalendar'
,  TransportResource = 'TransportResource'
,  Review = 'Review'
,  BookingCalendar = 'BookingCalendar'

   }