export interface AgencyDbType {
agencyId: number;
agencyName: string;
contactId: number;
activeInsurance: boolean;
insuranceURL: string;
insuranceExpery: string;
publisherId: number;
createdById: number;
isActive: boolean;
agencyBidId: number;
agencyFavoriteId: number;
agencyOfferId: number;
agencyDealId: number;
trustedPartnerIdPool: number;
extendedNetworkIdPool: number;
guideReviewINIdPool: number;
agencyReviewINIdPool: number;
touristReviewINIdPool: number;
guideReviewOUTIdPool: number;
agencyReviewOUTIdPool: number;
touristReviewOUTIdPool: number;
agencyMediaLibraryId: number;
isRomanian: boolean;
holidayCalendarId: number;
specializedAgency: string;
lastModified: string;
timeCreated: string;
}
